### PR TITLE
Make sure to only call eieio--class-name on a class

### PR DESCRIPTION
**Pull request by npostavs**
Should fix magit/forge#159

### CODE REVIEW

**Comment by tarsius** [comment]
Thanks!

I have extended the commit message and added an entry to the changelog.

**Comment by npostavs** [comment]
> Since Emacs 27 symbols are used as type descriptor again (and records
are still being used for eieio objects).

The change is actually on the emacs-26 right now (i.e., planned for 26.3), but due to this breakage (and possibly one other case I saw on StackExchange) I'm thinking about reverting it.

(also, it's conditional on `eieio-backwards-compatility` being `t` (the default))

**Comment by tarsius** [comment]
> due to this breakage (and possibly one other case I saw on StackExchange) I'm thinking about reverting it.

Well Magit touched internals it wasn't supposed to touch (but had to), so I don't think that's a reason not to improve the internals.

**Comment by npostavs** [comment]
Emacs point releases have a bit higher expectations not to break things, but yeah, I'm still leaning to keeping it in at the moment.

**Comment by greggroth** [comment]
Do you plan on cutting a release with this fix soon?

**Comment by skuro** [comment]
Yet another kind request to cut a release please :pray:

**Comment by tarsius** [comment]
Tataaa!

https://emacsair.me/2019/12/06/many-releases/

**Pull request merged**
